services:
  - type: web
    name: rams-form
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    preDeployCommand: |
      php artisan config:clear
      php artisan cache:clear
      php artisan migrate --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://rams-form.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1qr3rripnbc73emmb90-a.singapore-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: ramsform_db
      - key: DB_USERNAME
        value: admin_user
      - key: DB_PASSWORD
        value: 8tNH5yFwFbP2oQHaYoZSqMCWrVhLiQ2q
      - key: VITE_APP_NAME
        value: Rams Form
